import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart'; // NEW: Hive import
import 'models/flashcard.dart'; // Import your model
import 'screens/deck_selection_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Hive and register the adapter 
  // generated by the build runner.
  await Hive.initFlutter();
  Hive.registerAdapter(FlashcardAdapter());
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title:'Study Cards',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home:const DeckSelectionScreen(),
    );
  }
}